export { default as BVPlatformButton } from './BVPlatformButton.vue'
export { detectPlatform, resolveDownload, resolveManifestUrl, defaultLabels } from './platform'
export type { BVPlatformManifest, BVPlatformEntry, BVPlatformId } from './platform'
export type { BVPlatformButtonProps } from './BVPlatformButton.types'
export { default as BVMoreButton } from './BVMoreButton.vue'
export type { BVMoreButtonItem, BVMoreButtonProps } from './BVMoreButton.types'
